### ISSUE TITLE
faltan ceros

### ISSUE THREAD

**Issue by jackievivianv** [4GeeksAcademy/cpgravina-clase17-simple-counter#3]
Hola Camille!, tu proyecto está muy bien, solo que le faltan "0", el ejercicio era con más ceros para que sea un contador extenso y puedan hacer una lógica algo más compleja. 

Porfa si puedes agrégale eso, y vuélvelo a enviar. 
Gracias! <3

**Comment by cpgravina** [comment]
Hecho! Gracias por el feedback

**Comment by cpgravina** [comment]
Fixed
